import { execFile as execFileCallback } from 'node:child_process';
import { promisify } from 'node:util';
import { access, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

const execFile = promisify(execFileCallback);
const root = process.cwd();
const knowledgeDir = path.join(root, 'knowledge');
const rawDir = path.join(knowledgeDir, 'raw');
const publicKnowledgeDir = path.join(root, 'public/knowledge');
const tsOutput = path.join(root, 'src/lib/generatedKnowledge.ts');
const dartOutput = path.join(root, 'lib/src/generated/generated_knowledge.dart');
const pdfExtractor = path.join(root, 'scripts/extract_pdf_pages.py');
const knowledgePythonCandidates = [
  path.join(root, '.venv-knowledge/bin/python3'),
  path.join(root, '.venv-knowledge/bin/python'),
  'python3',
];

const manifest = JSON.parse(await readFile(path.join(knowledgeDir, 'source_manifest.json'), 'utf8'));
const entrySeed = JSON.parse(await readFile(path.join(knowledgeDir, 'entry_seed.json'), 'utf8'));
const mergeOnly = process.env.KB_MERGE_ONLY === '1';
let existingKnowledge = null;
if (mergeOnly) {
  try {
    existingKnowledge = JSON.parse(await readFile(path.join(knowledgeDir, 'offline_knowledge.json'), 'utf8'));
  } catch {
    existingKnowledge = null;
  }
}
await mkdir(rawDir, { recursive: true });
await mkdir(publicKnowledgeDir, { recursive: true });

async function resolveKnowledgePython() {
  for (const candidate of knowledgePythonCandidates) {
    try {
      if (candidate.includes(path.sep)) {
        await access(candidate);
      }
      return candidate;
    } catch {
      // Try next candidate.
    }
  }
  return 'python3';
}

const knowledgePython = await resolveKnowledgePython();
const browserUserAgent =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36';
const merckTopicSitemaps = [
  {
    sitemapId: 'merck-home-topic-sitemap',
    sitemapUrl: 'https://www.msdmanuals.com/sitemaps/home-topic.xml.gz',
    prefix: 'https://www.msdmanuals.com/home/',
    sourceIdPrefix: 'merck-home-topic',
    authority: 'MSD Manual',
    titlePrefix: 'MSD Manual Consumer Topic',
  },
  {
    sitemapId: 'merck-professional-topic-sitemap',
    sitemapUrl: 'https://www.msdmanuals.com/sitemaps/professional-topic.xml.gz',
    prefix: 'https://www.msdmanuals.com/professional/',
    sourceIdPrefix: 'merck-professional-topic',
    authority: 'Merck Manual Professional Edition',
    titlePrefix: 'Merck Manual Professional Topic',
  },
];
const merckTopicConcurrency = Number.parseInt(process.env.MERCK_TOPIC_CONCURRENCY ?? '8', 10);
const merckTopicRetries = Number.parseInt(process.env.MERCK_TOPIC_RETRIES ?? '3', 10);
const merckTopicLimit = Number.parseInt(process.env.MERCK_TOPIC_LIMIT ?? '0', 10);
const cdcAzTopicConcurrency = Number.parseInt(process.env.CDC_AZ_CONCURRENCY ?? '6', 10);
const cdcAzTopicLimit = Number.parseInt(process.env.CDC_AZ_LIMIT ?? '120', 10);
const dartSeedLimit = Number.parseInt(process.env.DART_KNOWLEDGE_LIMIT ?? '1800', 10);
const cdcAzTopicPatterns = [
  /abusive head trauma/i,
  /asthma/i,
  /anthrax/i,
  /carbon monoxide/i,
  /concussion/i,
  /drowning/i,
  /electrical safety/i,
  /falls?/i,
  /floods?/i,
  /food poisoning/i,
  /heat/i,
  /injury/i,
  /lead poisoning/i,
  /overdose/i,
  /poisonous plants?/i,
  /radiation/i,
  /rabies/i,
  /respiratory/i,
  /stroke/i,
  /ticks?/i,
  /traumatic brain injury/i,
  /venomous snakes/i,
  /venomous spiders/i,
];

function slugExt(contentType, url) {
  if (contentType?.includes('pdf') || url.toLowerCase().endsWith('.pdf')) return 'pdf';
  if (contentType?.includes('csv') || url.toLowerCase().endsWith('.csv')) return 'csv';
  if (contentType?.includes('markdown') || url.toLowerCase().endsWith('.md')) return 'md';
  if (contentType?.includes('plain') || url.toLowerCase().endsWith('.txt')) return 'txt';
  return 'html';
}

function stripHtmlTitle(html) {
  const match = html.match(/<title[^>]*>(.*?)<\/title>/is);
  return (match?.[1] ?? '').replace(/\s+/g, ' ').trim();
}

function isBlockedOrErrorHtml(html) {
  const title = stripHtmlTitle(html);
  const normalized = normalizeWhitespace(html).toLowerCase();
  return (
    /error:\s*the request could not be satisfied/i.test(title) ||
    normalized.includes('error: the request could not be satisfied') ||
    normalized.includes('generated by cloudfront') ||
    normalized.includes('<h1>403 error</h1>')
  );
}

function stripMarkdownTitle(markdown) {
  const match = markdown.match(/^#\s+(.+)$/m);
  return match?.[1]?.trim() ?? '';
}

function escapeTs(value) {
  return JSON.stringify(value, null, 2);
}

function escapeDartString(value) {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$').replace(/\n/g, '\\n');
}

function dartList(values, indent = '        ') {
  if (!values.length) return 'const <String>[]';
  return '[\n' + values.map((v) => `${indent}'${escapeDartString(v)}'`).join(',\n') + ',\n      ]';
}

function normalizeWhitespace(value) {
  return value.replace(/\r/g, '').replace(/\u00a0/g, ' ').replace(/\s+/g, ' ').trim();
}

function splitSentences(value) {
  return value
    .replace(/\r/g, '\n')
    .split(/\n|(?<=[.!?。！？])\s+/)
    .map((line) => line.trim())
    .filter(Boolean);
}

function dedupeStrings(values) {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean)));
}

function decodeHtmlEntities(value) {
  return value
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>');
}

function stripHtml(html) {
  return normalizeWhitespace(
    decodeHtmlEntities(
      html
        .replace(/<script[\s\S]*?<\/script>/gi, ' ')
        .replace(/<style[\s\S]*?<\/style>/gi, ' ')
        .replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ')
        .replace(/<svg[\s\S]*?<\/svg>/gi, ' ')
        .replace(/<(br|\/p|\/div|\/li|\/h1|\/h2|\/h3|\/h4|\/section|\/article)>/gi, '\n')
        .replace(/<[^>]+>/g, ' '),
    ),
  );
}

function stripHtmlTags(value) {
  return normalizeWhitespace(decodeHtmlEntities((value ?? '').replace(/<[^>]+>/g, ' ')));
}

function normalizeComparableUrl(value) {
  if (!value) {
    return '';
  }

  try {
    const url = new URL(value);
    url.hash = '';
    url.search = '';
    return url.toString().replace(/\/$/, '');
  } catch {
    return value.replace(/[#?].*$/, '').replace(/\/$/, '');
  }
}

function slugifySourceId(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 96);
}

function sourceTerms(source) {
  const terms = [];
  for (const text of [source.id, source.authority, source.title]) {
    const normalized = (text ?? '').toLowerCase();
    for (const token of normalized.split(/[^a-z0-9\u4e00-\u9fff]+/).filter(Boolean)) {
      if (token.length >= 2) {
        terms.push(token);
      }
    }
  }
  return dedupeStrings(terms).slice(0, 16);
}

function sourceTopicProfile(source) {
  const authority = (source.authority ?? '').toLowerCase();
  const title = (source.title ?? '').toLowerCase();
  const url = normalizeComparableUrl(source.finalUrl ?? source.url ?? '').toLowerCase();
  const sourceId = (source.id ?? '').toLowerCase();
  const haystack = `${authority} ${title} ${url} ${sourceId}`;
  const tags = [];
  let category = null;
  let priorityFloor = null;

  if (authority.includes('national park service') || url.includes('nps.gov')) {
    tags.push('survival', 'government guidance', 'outdoor survival');
    if (/trip-planning-guide|gtgemergencyplan|10essentials|gear checklist|make-a-plan/.test(haystack)) {
      tags.push(
        'survival_prep',
        'trip plan',
        'route sharing',
        'communication plan',
        'ten essentials',
        'weather turnaround',
      );
      category = 'survival_prep';
      priorityFloor = 8;
    } else if (/wilderness-travel-basics|wilderness/.test(haystack)) {
      tags.push(
        'survival_field',
        'lost',
        'shelter',
        'water purification',
        'signaling',
        'navigation',
      );
      category = 'survival_field';
      priorityFloor = 8;
    }
  }

  if (authority.includes('national weather service') || authority.includes('noaa') || url.includes('weather.gov')) {
    tags.push('survival', 'survival_hazards', 'weather safety', 'government guidance');
    category = category ?? 'survival_hazards';
    priorityFloor = Math.max(priorityFloor ?? 0, 8);
    if (/lightning/.test(haystack)) {
      tags.push('lightning', '雷击', '雷暴');
    }
    if (/flood/.test(haystack)) {
      tags.push('flood', 'flash flood', '山洪', '洪水');
    }
    if (/heat/.test(haystack)) {
      tags.push('heat illness', '中暑', '热射病');
    }
    if (/cold|winter|hypothermia|frostbite/.test(haystack)) {
      tags.push('hypothermia', '失温', '严寒', '冻伤');
    }
  }

  if (authority.includes('cdc')) {
    if (/niosh\/outdoor-workers|\/ticks\/|\/winter-weather\/|\/extreme-heat\/|outdoor workers|venomous snakes|venomous spiders|poisonous plants|ticks?|heat stress/.test(haystack)) {
      tags.push('survival', 'survival_hazards', 'government guidance');
      category = category ?? 'survival_hazards';
      priorityFloor = Math.max(priorityFloor ?? 0, 8);
      if (/venomous snakes|snake/.test(haystack)) {
        tags.push('snake bite', '蛇咬', '毒蛇');
      }
      if (/venomous spiders|spider/.test(haystack)) {
        tags.push('spider bite', '毒蜘蛛');
      }
      if (/poisonous plants/.test(haystack)) {
        tags.push('poisonous plants', '毒植物');
      }
      if (/ticks?/.test(haystack)) {
        tags.push('tick bite', '蜱虫');
      }
      if (/heat stress|extreme-heat/.test(haystack)) {
        tags.push('heat illness', '中暑');
      }
      if (/winter-weather|hypothermia|frostbite/.test(haystack)) {
        tags.push('hypothermia', '失温', '冻伤');
      }
    }

    if (/radiation-emergencies|radiation emergencies|nuclear|radiological|dirty bomb/.test(haystack)) {
      tags.push(
        'crisis_radiation',
        'nuclear emergency',
        'radiation emergency',
        'dirty bomb',
        'fallout',
        'government guidance',
      );
      category = category ?? 'crisis_radiation';
      priorityFloor = Math.max(priorityFloor ?? 0, 8);
    }

    if (/anthrax|bioterrorism|pandemic flu|pandemic/.test(haystack)) {
      tags.push(
        'crisis_bio',
        'biohazard',
        'biological attack',
        'pandemic',
        'government guidance',
      );
      category = category ?? 'crisis_bio';
      priorityFloor = Math.max(priorityFloor ?? 0, 8);
    }
  }

  if (authority.includes('ready.gov') || url.includes('ready.gov')) {
    tags.push('civil defense', 'government guidance');

    if (/radiation|nuclear|radiological/.test(haystack)) {
      tags.push('crisis_radiation', 'nuclear emergency', 'radiation emergency', 'fallout');
      category = category ?? 'crisis_radiation';
      priorityFloor = Math.max(priorityFloor ?? 0, 8);
    }

    if (/biohazard|pandemic|hazmat|anthrax/.test(haystack)) {
      tags.push('crisis_bio', 'biohazard', 'pandemic', 'chemical exposure');
      category = category ?? 'crisis_bio';
      priorityFloor = Math.max(priorityFloor ?? 0, 8);
    }

    if (/cybersecurity|get-tech-ready|power-outages|shields-ready/.test(haystack)) {
      tags.push(
        'crisis_cyber',
        'cyberattack',
        'infrastructure failure',
        'communications outage',
        'power outage',
      );
      category = category ?? 'crisis_cyber';
      priorityFloor = Math.max(priorityFloor ?? 0, 8);
    }

    if (/explosions|public-spaces|active shooter|shelter/.test(haystack)) {
      tags.push('crisis_conflict', 'explosion', 'shelter in place', 'hard cover');
      category = category ?? 'crisis_conflict';
      priorityFloor = Math.max(priorityFloor ?? 0, 8);
    }
  }

  if (sourceId.startsWith('fm-21-76') || sourceId.startsWith('fm-3-05-70')) {
    tags.push('survival manual', 'fieldcraft', 'extreme survival');
  }

  return {
    tags: dedupeStrings(tags),
    category,
    priorityFloor,
  };
}

function entryPriorityForSource(source) {
  let priority = 5;

  if (source.id.startsWith('fm-21-76')) {
    priority = Math.max(priority, 7);
  }
  if (source.id.startsWith('merck-')) {
    priority = Math.max(priority, 7);
  }
  if (source.id.startsWith('cdc-az-')) {
    priority = Math.max(priority, 7);
  }
  if (
    source.id.startsWith('who-') ||
    source.id.startsWith('redcross-') ||
    source.id.startsWith('ninds-') ||
    source.id.startsWith('niddk-') ||
    source.id.startsWith('samhsa-') ||
    source.id.startsWith('stop-the-bleed')
  ) {
    priority = 7;
  }
  if (source.id.startsWith('hf-')) {
    priority = 5;
  }
  if (source.authority.includes('CDC') || source.authority.includes('NHS') || source.authority.includes('MedlinePlus')) {
    priority = Math.max(priority, 6);
  }
  if (source.authority.includes('Ready.gov')) {
    priority = Math.max(priority, 6);
  }

  const topicProfile = sourceTopicProfile(source);
  if (topicProfile.priorityFloor != null) {
    priority = Math.max(priority, topicProfile.priorityFloor);
  }

  return priority;
}

function severityForPriority(priority) {
  if (priority >= 10) return 'critical';
  if (priority >= 7) return 'high';
  return 'medium';
}

function summarizeChunk(text) {
  const sentences = splitSentences(text);
  const summary = normalizeWhitespace(sentences[0] ?? text).slice(0, 180);
  const steps = dedupeStrings(sentences.slice(1, 5).map((item) => normalizeWhitespace(item))).slice(0, 4);
  return {
    summary: summary || 'See source excerpt.',
    steps: steps.length > 0 ? steps : [normalizeWhitespace(text).slice(0, 280)],
  };
}

function chunkParagraphs(paragraphs, maxChars = 1100) {
  const chunks = [];
  let current = [];
  let currentLength = 0;

  for (const paragraph of paragraphs) {
    const text = normalizeWhitespace(paragraph);
    if (!text) {
      continue;
    }

    if (text.length > maxChars * 1.25) {
      const sentences = splitSentences(text);
      let sentenceBucket = [];
      let sentenceLength = 0;
      for (const sentence of sentences) {
        if (sentenceLength + sentence.length > maxChars && sentenceBucket.length > 0) {
          chunks.push(sentenceBucket.join(' '));
          sentenceBucket = [];
          sentenceLength = 0;
        }
        sentenceBucket.push(sentence);
        sentenceLength += sentence.length + 1;
      }
      if (sentenceBucket.length > 0) {
        chunks.push(sentenceBucket.join(' '));
      }
      continue;
    }

    if (currentLength + text.length > maxChars && current.length > 0) {
      chunks.push(current.join('\n\n'));
      current = [];
      currentLength = 0;
    }

    current.push(text);
    currentLength += text.length + 2;
  }

  if (current.length > 0) {
    chunks.push(current.join('\n\n'));
  }

  return chunks.map((chunk) => normalizeWhitespace(chunk)).filter((chunk) => chunk.length >= 80);
}

function buildChunkEntries(source, chunks, category = '全文知识块') {
  const priority = entryPriorityForSource(source);
  const severity = severityForPriority(priority);
  const topicProfile = sourceTopicProfile(source);
  const effectiveCategory = category.startsWith('全文') && topicProfile.category ? topicProfile.category : category;
  const tags = dedupeStrings([effectiveCategory, ...topicProfile.tags, source.authority, source.title, ...sourceTerms(source)]);
  const aliases = dedupeStrings([source.title, source.authority, source.id, ...topicProfile.tags]).slice(0, 12);

  return chunks.map((chunk, index) => {
    const { summary, steps } = summarizeChunk(chunk);
    const titleSeed = splitSentences(chunk)[0] ?? summary;
    const title = `${source.title} #${index + 1} ${normalizeWhitespace(titleSeed).slice(0, 48)}`.trim();
    return {
      id: `${source.id}-chunk-${String(index + 1).padStart(4, '0')}`,
      title,
      summary,
      steps,
      contraindications: [],
      escalation: `原始来源：${source.authority} / ${source.title}`,
      tags,
      aliases,
      source: `${source.authority}: ${source.title}`,
      sourceId: source.id,
      sourceUrl: source.finalUrl,
      priority,
      category: effectiveCategory,
      locale: 'en',
      severity,
    };
  });
}

function applySourceTopicProfile(entry, source) {
  const topicProfile = source ? sourceTopicProfile(source) : { tags: [], category: null, priorityFloor: null };
  const category =
    topicProfile.category && /^全文/.test(entry.category)
      ? topicProfile.category
      : entry.category;
  const priority =
    topicProfile.priorityFloor != null
      ? Math.max(entry.priority, topicProfile.priorityFloor)
      : entry.priority;

  return {
    ...entry,
    category,
    tags: dedupeStrings([category, ...entry.tags, ...topicProfile.tags]),
    aliases: dedupeStrings([...entry.aliases, ...topicProfile.tags]).slice(0, 16),
    sourceUrl: entry.sourceUrl || source?.finalUrl || source?.url || '',
    priority,
    severity: severityForPriority(priority),
  };
}

function parseCsv(text) {
  const rows = [];
  let current = '';
  let row = [];
  let inQuotes = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (char === '"') {
      if (inQuotes && next === '"') {
        current += '"';
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === ',' && !inQuotes) {
      row.push(current);
      current = '';
      continue;
    }

    if ((char === '\n' || char === '\r') && !inQuotes) {
      if (char === '\r' && next === '\n') {
        index += 1;
      }
      row.push(current);
      current = '';
      if (row.some((cell) => cell.length > 0)) {
        rows.push(row);
      }
      row = [];
      continue;
    }

    current += char;
  }

  if (current.length > 0 || row.length > 0) {
    row.push(current);
    rows.push(row);
  }

  const [header = [], ...dataRows] = rows;
  return dataRows.map((cells) => Object.fromEntries(header.map((key, idx) => [key, cells[idx] ?? ''])));
}

function maybeParseJsonArray(value) {
  const trimmed = value.trim();
  if (!trimmed.startsWith('[') || !trimmed.endsWith(']')) {
    return null;
  }

  try {
    const parsed = JSON.parse(trimmed);
    return Array.isArray(parsed) ? parsed.map((item) => `${item}`) : null;
  } catch {
    return null;
  }
}

function cleanDatasetField(value) {
  return value
    .replace(/^"+|"+$/g, '')
    .replace(/^Answer:\s*/i, '')
    .replace(/\\"/g, '"')
    .trim();
}

function extractDatasetTexts(value) {
  const cleaned = cleanDatasetField(value);
  const parsed = maybeParseJsonArray(cleaned);
  if (parsed) {
    return parsed.map((item) => cleanDatasetField(item));
  }
  return [cleaned];
}

function extractDatasetSteps(answer) {
  const texts = extractDatasetTexts(answer);
  const lines = [];

  for (const text of texts) {
    for (const segment of splitSentences(text)) {
      const cleaned = segment
        .replace(/^[\-\u2022*]\s*/, '')
        .replace(/^\d+[.)]\s*/, '')
        .replace(/^If\s+/i, '')
        .replace(/^Then\s+/i, '')
        .trim();

      if (!cleaned || cleaned.length < 12) {
        continue;
      }

      lines.push(cleaned);
    }
  }

  return dedupeStrings(lines).slice(0, 4);
}

async function downloadWithCurl(item) {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'beacon-knowledge-'));
  const tempFile = path.join(tempDir, item.id);
  try {
    const { stdout } = await execFile('curl', [
      '-L',
      '-sS',
      '--compressed',
      '--retry',
      '3',
      '--retry-all-errors',
      '--retry-delay',
      '2',
      '-A',
      browserUserAgent,
      '-H',
      'accept: text/html,text/plain,text/markdown,text/csv,application/pdf;q=0.9,*/*;q=0.8',
      '-H',
      'accept-language: en-US,en;q=0.9',
      '-o',
      tempFile,
      '-w',
      '%{content_type}\n%{url_effective}',
      item.url,
    ]);

    const [contentType = '', finalUrl = item.url] = stdout.trim().split('\n');
    const bytes = new Uint8Array(await readFile(tempFile));
    return { bytes, contentType, finalUrl };
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

async function downloadSource(item) {
  for (let attempt = 1; attempt <= merckTopicRetries; attempt += 1) {
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 30_000);
      const response = await fetch(item.url, {
        headers: {
          'user-agent': browserUserAgent,
          accept: 'text/html,text/plain,text/markdown,text/csv,application/pdf;q=0.9,*/*;q=0.8',
          'accept-language': 'en-US,en;q=0.9',
        },
        redirect: 'follow',
        signal: controller.signal,
      }).finally(() => clearTimeout(timeout));

      if (!response.ok) {
        throw new Error(`HTTP ${response.status} ${response.statusText}`);
      }

      return {
        bytes: new Uint8Array(await response.arrayBuffer()),
        contentType: response.headers.get('content-type') ?? '',
        finalUrl: response.url,
      };
    } catch (error) {
      if (attempt === merckTopicRetries) {
        return downloadWithCurl(item);
      }
      await new Promise((resolve) => setTimeout(resolve, 500 * attempt));
    }
  }
}

async function fetchSitemapTopicUrls(sitemap) {
  const xml = await downloadSource({
    id: sitemap.sitemapId,
    url: sitemap.sitemapUrl,
    authority: sitemap.authority,
    title: sitemap.titlePrefix,
  });
  const text = Buffer.from(xml.bytes).toString('utf8');
  const matches = Array.from(text.matchAll(/<loc>(.*?)<\/loc>/g)).map((match) => match[1]);
  const urls = matches
    .filter((url) => url.startsWith(sitemap.prefix))
    .map((url) => `${url}${url.includes('?') ? '&' : '?'}media=print`);
  return merckTopicLimit > 0 ? urls.slice(0, merckTopicLimit) : urls;
}

function alternateTopicUrlForSitemap(url, sitemap) {
  if (sitemap.sourceIdPrefix !== 'merck-professional-topic') {
    return null;
  }
  return url.replace('https://www.msdmanuals.com/professional/', 'https://www.merckmanuals.com/professional/');
}

async function fetchCdcAzTopicSeeds(existingSources) {
  const downloaded = await downloadSource({
    id: 'cdc-health-topics-a-z-index',
    url: 'https://www.cdc.gov/az/az-export.json',
    authority: 'CDC',
    title: 'CDC Health Topics A-Z Index',
  });

  const knownUrls = new Set(
    existingSources.flatMap((source) =>
      [source.url, source.finalUrl].map((value) => normalizeComparableUrl(value)).filter(Boolean),
    ),
  );
  const seenUrls = new Set();
  const items = JSON.parse(Buffer.from(downloaded.bytes).toString('utf8'));
  const seeds = [];

  for (const item of items) {
    const title = stripHtmlTags(item.title);
    const url = normalizeComparableUrl(item.url);
    const haystack = `${title} ${url}`.toLowerCase();
    if (!url.startsWith('https://www.cdc.gov/')) {
      continue;
    }
    if (!cdcAzTopicPatterns.some((pattern) => pattern.test(haystack))) {
      continue;
    }
    if (knownUrls.has(url) || seenUrls.has(url)) {
      continue;
    }

    const urlPath = new URL(url).pathname.replace(/(^\/|\/$)/g, '').replace(/\/+/g, '-');
    const sourceId = `cdc-az-${slugifySourceId(urlPath || title || `topic-${seeds.length + 1}`)}`;
    seeds.push({
      id: sourceId,
      url,
      authority: 'CDC',
      title: title || `CDC Topic ${seeds.length + 1}`,
    });
    seenUrls.add(url);
  }

  seeds.sort((left, right) => left.title.localeCompare(right.title));
  return cdcAzTopicLimit > 0 ? seeds.slice(0, cdcAzTopicLimit) : seeds;
}

async function mapWithConcurrency(items, limit, worker) {
  const results = [];
  let cursor = 0;

  async function runWorker() {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await worker(items[index], index);
    }
  }

  const workers = Array.from({ length: Math.min(limit, items.length) }, () => runWorker());
  await Promise.all(workers);
  return results;
}

async function extractPdfPages(rawPath) {
  const { stdout } = await execFile(knowledgePython, [pdfExtractor, rawPath], {
    maxBuffer: 1024 * 1024 * 64,
  });
  const parsed = JSON.parse(stdout);
  return (parsed.pages ?? [])
    .map((page) => ({
      page: page.page,
      text: normalizeWhitespace(page.text ?? ''),
    }))
    .filter((page) => page.text.length >= 120);
}

function buildPdfChunkEntries(source, pages) {
  const chunks = [];
  for (const page of pages) {
    const paragraphs = page.text
      .split(/\n{2,}/)
      .map((part) => normalizeWhitespace(part))
      .filter((part) => part.length >= 50);
    for (const chunk of chunkParagraphs(paragraphs)) {
      chunks.push(`Page ${page.page}. ${chunk}`);
    }
  }
  return buildChunkEntries(source, chunks, '全文手册');
}

function extractMainHtml(html) {
  const mainMatch = html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i);
  if (!mainMatch) {
    return html;
  }

  return mainMatch[1]
    .replace(/<nav[\s\S]*?<\/nav>/gi, ' ')
    .replace(/<footer[\s\S]*?<\/footer>/gi, ' ');
}

function buildHtmlChunkEntries(source, html) {
  const title = stripHtmlTitle(html);
  const plain = stripHtml(extractMainHtml(html));
  const paragraphs = plain
    .split(/\n{2,}/)
    .map((part) => normalizeWhitespace(part))
    .filter(
      (part) =>
        part.length >= 60 &&
        !/^cookie|^menu|^search$/i.test(part) &&
        !/^(msd manual|merck manual|consumer version|professional edition)$/i.test(part) &&
        !/^(skip to|open menu close menu|an official website of the united states government)/i.test(part) &&
        !/^(accessibility privacy policy|foia notices|vulnerability disclosure policy|usa\.gov)/i.test(part) &&
        !/^(national park service search search this site|explore this park|loading alerts alerts in effect)/i.test(part) &&
        !/here's how you know official websites use \.gov/i.test(part),
    );
  const chunks = chunkParagraphs(paragraphs.length > 0 ? paragraphs : [plain]);
  const effectiveSource = title ? { ...source, title } : source;
  return buildChunkEntries(effectiveSource, chunks, '全文网页');
}

function buildTextChunkEntries(source, text) {
  const paragraphs = text
    .replace(/\r/g, '\n')
    .split(/\n{2,}/)
    .map((part) => normalizeWhitespace(part))
    .filter((part) => part.length >= 60);
  return buildChunkEntries(source, chunkParagraphs(paragraphs), '全文文档');
}

function buildCsvChunkEntries(source, csvText) {
  const rows = parseCsv(csvText);
  const priority = entryPriorityForSource(source);
  const severity = severityForPriority(priority);
  const tags = dedupeStrings([source.authority, source.title, source.id, 'dataset', 'csv', ...sourceTerms(source)]);

  return rows
    .map((row, index) => {
      const question = cleanDatasetField(row.question ?? row.Question ?? row.prompt ?? '');
      const answer = cleanDatasetField(row.answer ?? row.Answer ?? row.response ?? '');
      const texts = [question, ...extractDatasetTexts(answer)].map((item) => normalizeWhitespace(item)).filter(Boolean);
      const joined = texts.join(' ');
      if (joined.length < 40) {
        return null;
      }

      const summary = question || texts[0] || `Dataset row ${index + 1}`;
      const steps = extractDatasetSteps(answer);
      return {
        id: `${source.id}-row-${String(index + 1).padStart(4, '0')}`,
        title: `${source.title} Q${index + 1} ${summary.slice(0, 60)}`,
        summary,
        steps: steps.length > 0 ? steps : texts.slice(1, 5),
        contraindications: [],
        escalation: `Dataset source row ${index + 1} from ${source.title}`,
        tags,
        aliases: [question, source.title, source.authority].filter(Boolean),
        source: `${source.authority}: ${source.title}`,
        sourceId: source.id,
        sourceUrl: source.finalUrl,
        priority,
        category: '数据集知识块',
        locale: 'en',
        severity,
      };
    })
    .filter(Boolean);
}

function buildHuggingFaceDerivedEntries(sourceId, csvText) {
  const rows = parseCsv(csvText).map((row) => ({
    question: cleanDatasetField(row.question ?? ''),
    answer: cleanDatasetField(row.answer ?? ''),
  }));

  const mappings = [
    {
      id: 'hf-cardiac-arrest-cpr',
      title: '心搏骤停时的 CPR 与 AED',
      summary: '先呼救、立刻按压、尽快接 AED，连续不中断更关键。',
      category: '心搏骤停',
      priority: 8,
      tags: ['心搏骤停', 'CPR', 'AED', 'cardiac arrest'],
      aliases: ['心脏骤停', '没有呼吸心跳', '胸外按压'],
      contraindications: ['不要等待自然恢复', '不要长时间中断胸外按压'],
      escalation: '心搏骤停属于分秒级急症，必须持续 CPR 直到 AED 或专业救援接手。',
      patterns: [/cardiac arrest/i, /\bCPR\b/i, /\bAED\b/i],
      fallbackSteps: [
        '立即呼叫急救并确认附近是否有 AED。',
        '立刻开始高质量胸外按压，尽量减少中断。',
        'AED 到场后按语音提示操作，并持续 CPR 直到专业人员接手。',
      ],
    },
    {
      id: 'hf-choking-infant',
      title: '婴儿噎住时的急救',
      summary: '婴儿不能直接做成人海姆立克，要用拍背和胸部按压。',
      category: '窒息',
      priority: 7,
      tags: ['婴儿噎住', '宝宝噎住', 'infant choking'],
      aliases: ['小孩卡住了', '宝宝窒息', '婴儿呛住'],
      contraindications: ['不要盲目伸手抠看不见的异物', '不要给完全噎住的婴儿喂水'],
      escalation: '若婴儿反应差、发青或失去意识，立刻呼叫急救并按婴儿 CPR 流程处理。',
      patterns: [/baby is chocking/i, /infant choking/i, /baby is choking/i],
      fallbackSteps: [
        '让婴儿面朝下俯卧在前臂上，头低于胸口，进行 5 次有力拍背。',
        '若无效，翻正后在胸骨中下段进行 5 次胸部按压。',
        '在拍背和胸部按压之间循环，直到异物排出或急救人员到场。',
      ],
    },
    {
      id: 'hf-choking-alone',
      title: '独自噎住时的自救',
      summary: '先设法呼叫急救，再借助硬物进行自我腹部冲击。',
      category: '窒息',
      priority: 7,
      tags: ['独自噎住', 'self choking', 'alone choking'],
      aliases: ['一个人卡住了', '自己被卡住', '噎住求救'],
      contraindications: ['不要反复喝水试图冲下去', '不要继续吞咽更多食物'],
      escalation: '若无法发声、呼吸迅速恶化或即将失去意识，必须尽快引起他人注意并呼救。',
      patterns: [/all alone/i, /self.*choking/i, /I am chocking/i],
      fallbackSteps: [
        '立刻拨打急救电话并尽量保持线路接通。',
        '用拳头顶住上腹部，或把上腹部快速压向椅背、桌角等坚硬边缘。',
        '持续重复冲击动作，直到异物排出或有人接手救援。',
      ],
    },
    {
      id: 'hf-electrical-burn',
      title: '电击伤与电烧伤处理',
      summary: '先断电再接触伤者，外观轻也可能有严重内伤。',
      category: '烧伤',
      priority: 7,
      tags: ['电击', '电烧伤', 'electrical burn', 'electric shock'],
      aliases: ['触电了', '被电到了', '高压电'],
      contraindications: ['不要在未断电前直接触碰伤者', '不要只看表面小伤就掉以轻心'],
      escalation: '电击伤可能伴发心律失常和深部组织损伤，应尽快急救和医疗评估。',
      patterns: [/electrical burn/i, /electric shock/i],
      fallbackSteps: [
        '先切断电源，或用绝缘物把伤者与电源分离。',
        '确认安全后检查意识与呼吸，必要时立即开始 CPR。',
        '用无粘性敷料覆盖烧伤面，尽快联系急救。',
      ],
    },
    {
      id: 'hf-fracture-stabilization',
      title: '骨折后的现场稳定',
      summary: '先固定再搬运，减少再次错位和出血。',
      category: '致命外伤',
      priority: 7,
      tags: ['骨折', 'fracture', 'broken bone', '夹板'],
      aliases: ['断骨', '骨头断了', '疑似骨折'],
      contraindications: ['不要强行复位', '不要让伤者带伤行走'],
      escalation: '若骨头外露、脊柱受伤或合并大量出血，应立即急救转运。',
      patterns: [/broken bones/i, /fracture/i, /broken bone/i],
      fallbackSteps: [
        '让伤者保持不动，先处理明显大出血。',
        '用夹板、木板或卷起的硬物固定受伤部位上下关节。',
        '抬高和冰敷只能在不增加疼痛与变形时进行，并尽快就医。',
      ],
    },
    {
      id: 'hf-heat-stroke-cooling',
      title: '热射病的快速降温动作',
      summary: '高热加意识改变要边呼救边强力降温。',
      category: '高温中暑',
      priority: 7,
      tags: ['热射病', 'heat stroke', '高热', '中暑昏迷'],
      aliases: ['中暑很严重', '晒到意识不清', '热晕了'],
      contraindications: ['不要等待自然恢复', '不要给意识不清者灌水'],
      escalation: '热射病可致命，应立刻急救并持续降温到专业救援接手。',
      patterns: [/heat stroke/i],
      fallbackSteps: [
        '立即呼叫急救，把人转移到阴凉通风处并去除多余衣物。',
        '持续用冷水、湿毛巾或冰袋降温，重点放在颈部、腋下和腹股沟。',
        '如果患者意识不清，只维持气道和侧卧位，不要喂水。',
      ],
    },
  ];

  return mappings.map((mapping) => {
    const matchedRows = rows.filter((row) => {
      const combined = `${row.question}\n${row.answer}`;
      return mapping.patterns.some((pattern) => pattern.test(combined));
    });

    const extractedSteps = dedupeStrings(
      matchedRows.flatMap((row) => extractDatasetSteps(row.answer)),
    ).slice(0, 4);

    return {
      id: mapping.id,
      title: mapping.title,
      summary: mapping.summary,
      steps: extractedSteps.length > 0 ? extractedSteps : mapping.fallbackSteps,
      contraindications: mapping.contraindications,
      escalation: mapping.escalation,
      tags: Array.from(new Set([mapping.category, ...mapping.tags, 'huggingface', 'medical qa'])),
      aliases: mapping.aliases,
      sourceId,
      priority: mapping.priority,
      category: mapping.category,
    };
  });
}

const downloadedSources = existingKnowledge ? [...existingKnowledge.sources] : [];
const newlyDownloadedSources = [];
for (const item of manifest) {
  if (downloadedSources.some((source) => source.id === item.id)) {
    continue;
  }
  const downloaded = await downloadSource(item);
  const { bytes, contentType, finalUrl } = downloaded;
  const ext = slugExt(contentType, `${finalUrl} ${item.url}`);
  const rawPath = path.join(rawDir, `${item.id}.${ext}`);
  await writeFile(rawPath, bytes);

  let title = item.title ?? item.id;
  if (ext === 'html') {
    title = stripHtmlTitle(Buffer.from(bytes).toString('utf8')) || item.title || item.id;
  } else if (ext === 'md' || ext === 'txt') {
    title = stripMarkdownTitle(Buffer.from(bytes).toString('utf8')) || item.title || item.id;
  }

  const downloadedSource = {
    ...item,
    finalUrl,
    contentType,
    ext,
    fileName: path.relative(knowledgeDir, rawPath),
    title,
    downloadedAt: new Date().toISOString(),
  };
  downloadedSources.push(downloadedSource);
  newlyDownloadedSources.push(downloadedSource);
}

const sourceById = new Map(downloadedSources.map((item) => [item.id, item]));

const dynamicHtmlResults = [];
if (!mergeOnly) {
  const merckTopicUrlSets = new Map();
  for (const sitemap of merckTopicSitemaps) {
    const topicUrls = await fetchSitemapTopicUrls(sitemap);
    merckTopicUrlSets.set(sitemap.sourceIdPrefix, topicUrls);
    console.log(`Prepared ${topicUrls.length} URLs for ${sitemap.sourceIdPrefix}.`);
  }

  for (const sitemap of merckTopicSitemaps) {
    const topicUrls = merckTopicUrlSets.get(sitemap.sourceIdPrefix) ?? [];
    const results = await mapWithConcurrency(
      topicUrls,
      Math.max(1, merckTopicConcurrency),
      async (url, index) => {
        if ((index + 1) % 100 === 0 || index === 0) {
          console.log(`${sitemap.sourceIdPrefix}: ${index + 1}/${topicUrls.length}`);
        }
        const sourceId = `${sitemap.sourceIdPrefix}-${String(index + 1).padStart(4, '0')}`;
        try {
          const candidateUrls = [url, alternateTopicUrlForSitemap(url, sitemap)].filter(Boolean);
          let downloaded = null;
          for (const candidateUrl of candidateUrls) {
            try {
              downloaded = await downloadSource({
                id: sourceId,
                url: candidateUrl,
                authority: sitemap.authority,
                title: `${sitemap.titlePrefix} ${index + 1}`,
              });
              break;
            } catch {
              downloaded = null;
            }
          }
          if (!downloaded) {
            throw new Error(`Unable to download ${sourceId}`);
          }
          const html = Buffer.from(downloaded.bytes).toString('utf8');
          if (isBlockedOrErrorHtml(html)) {
            return null;
          }
          const title = stripHtmlTitle(html) || `${sitemap.titlePrefix} ${index + 1}`;
          const source = {
            id: sourceId,
            url: downloaded.finalUrl,
            authority: sitemap.authority,
            title,
            finalUrl: downloaded.finalUrl,
            contentType: downloaded.contentType,
            ext: 'html',
            fileName: '',
            downloadedAt: new Date().toISOString(),
          };
          const entries = buildHtmlChunkEntries(source, html).slice(0, 2);
          return { source, entries };
        } catch {
          return null;
        }
      },
    );
    dynamicHtmlResults.push(...results);
  }
}

const cdcAzTopicSeeds = await fetchCdcAzTopicSeeds(downloadedSources);
if (cdcAzTopicSeeds.length > 0) {
  console.log(`Prepared ${cdcAzTopicSeeds.length} CDC Health Topics A-Z emergency URLs.`);
  const cdcAzResults = await mapWithConcurrency(
    cdcAzTopicSeeds,
    Math.max(1, cdcAzTopicConcurrency),
    async (seed, index) => {
      if ((index + 1) % 25 === 0 || index === 0) {
        console.log(`cdc-az: ${index + 1}/${cdcAzTopicSeeds.length}`);
      }
      try {
        const downloaded = await downloadSource(seed);
        const html = Buffer.from(downloaded.bytes).toString('utf8');
        if (isBlockedOrErrorHtml(html)) {
          return null;
        }
        const title = stripHtmlTitle(html) || seed.title;
        const source = {
          ...seed,
          url: downloaded.finalUrl,
          finalUrl: downloaded.finalUrl,
          contentType: downloaded.contentType,
          ext: 'html',
          fileName: '',
          title,
          downloadedAt: new Date().toISOString(),
        };
        const entries = buildHtmlChunkEntries(source, html).slice(0, 2);
        return { source, entries };
      } catch {
        return null;
      }
    },
  );
  dynamicHtmlResults.push(...cdcAzResults);
}

for (const result of dynamicHtmlResults) {
  if (!result) {
    continue;
  }
  downloadedSources.push(result.source);
  sourceById.set(result.source.id, result.source);
}

const fulltextEntries = [];
for (const source of newlyDownloadedSources) {
  if (!source.fileName) {
    continue;
  }
  const rawPath = path.join(knowledgeDir, source.fileName);
  if (source.ext === 'pdf') {
    const pages = await extractPdfPages(rawPath);
    fulltextEntries.push(...buildPdfChunkEntries(source, pages));
    continue;
  }

  const rawText = await readFile(rawPath, 'utf8');
  if (source.ext === 'csv') {
    fulltextEntries.push(...buildCsvChunkEntries(source, rawText));
  } else if (source.ext === 'html') {
    fulltextEntries.push(...buildHtmlChunkEntries(source, rawText));
  } else {
    fulltextEntries.push(...buildTextChunkEntries(source, rawText));
  }
}

const derivedEntries = [];
const hfDatasetSource = newlyDownloadedSources.find((item) => item.id === 'hf-first-aid-dataset');
if (hfDatasetSource && !mergeOnly) {
  const hfRaw = await readFile(path.join(knowledgeDir, hfDatasetSource.fileName), 'utf8');
  derivedEntries.push(...buildHuggingFaceDerivedEntries(hfDatasetSource.id, hfRaw));
}

const normalizedCuratedEntries = [...entrySeed, ...derivedEntries].map((entry) => {
  const source = sourceById.get(entry.sourceId);
  if (!source) {
    throw new Error(`Unknown sourceId ${entry.sourceId} in entry ${entry.id}`);
  }

  return applySourceTopicProfile({
    id: entry.id,
    title: entry.title,
    summary: entry.summary,
    steps: entry.steps,
    contraindications: entry.contraindications,
    escalation: entry.escalation,
    tags: Array.from(new Set([entry.category, ...entry.tags])),
    aliases: entry.aliases,
    source: `${source.authority}: ${source.title}`,
    sourceId: source.id,
    sourceUrl: source.finalUrl,
    priority: entry.priority,
    category: entry.category,
    locale: 'zh-CN',
    severity: severityForPriority(entry.priority),
  }, source);
});

const normalizedEntries = mergeOnly
  ? [...(existingKnowledge?.entries ?? []).map((entry) => applySourceTopicProfile(entry, sourceById.get(entry.sourceId))), ...normalizedCuratedEntries]
  : normalizedCuratedEntries;

const dedupedEntries = [];
const seenIds = new Set();
const seenBodies = new Set();
for (const entry of [...normalizedEntries, ...fulltextEntries]) {
  if (seenIds.has(entry.id)) {
    continue;
  }
  const fingerprint = normalizeWhitespace([entry.title, entry.summary, ...entry.steps].join(' ')).slice(0, 1000);
  if (seenBodies.has(fingerprint)) {
    continue;
  }
  seenIds.add(entry.id);
  seenBodies.add(fingerprint);
  dedupedEntries.push(entry);
}

for (const result of dynamicHtmlResults) {
  if (!result) {
    continue;
  }
  for (const entry of result.entries) {
    if (seenIds.has(entry.id)) {
      continue;
    }
    const fingerprint = normalizeWhitespace([entry.title, entry.summary, ...entry.steps].join(' ')).slice(0, 1000);
    if (seenBodies.has(fingerprint)) {
      continue;
    }
    seenIds.add(entry.id);
    seenBodies.add(fingerprint);
    dedupedEntries.push(entry);
  }
}

const outputJson = {
  version: 2,
  generatedAt: new Date().toISOString(),
  sources: downloadedSources,
  entries: dedupedEntries,
};

await writeFile(path.join(knowledgeDir, 'offline_knowledge.json'), JSON.stringify(outputJson, null, 2) + '\n');
await writeFile(path.join(publicKnowledgeDir, 'offline_knowledge.json'), JSON.stringify(outputJson) + '\n');

const sourceSummary = downloadedSources.map((source) => ({
  id: source.id,
  authority: source.authority,
  title: source.title,
}));

const tsSource = `// Auto-generated by scripts/build_offline_knowledge.mjs\nexport const OFFLINE_KNOWLEDGE_SOURCES = ${escapeTs(sourceSummary)} as const;\n\nexport const OFFLINE_KNOWLEDGE_STATS = ${escapeTs({
  version: outputJson.version,
  sourceCount: downloadedSources.length,
  entryCount: dedupedEntries.length,
})} as const;\n`;
await writeFile(tsOutput, tsSource);

const dartSeedEntries = dedupedEntries
  .slice()
  .sort((a, b) => {
    if (b.priority !== a.priority) {
      return b.priority - a.priority;
    }
    return a.id.localeCompare(b.id);
  })
  .slice(0, dartSeedLimit);

const dartEntries = dartSeedEntries.map((entry) => `  KnowledgeEntry(\n      id: '${escapeDartString(entry.id)}',\n      title: '${escapeDartString(entry.title)}',\n      summary: '${escapeDartString(entry.summary)}',\n      steps: ${dartList(entry.steps)},\n      contraindications: ${dartList(entry.contraindications)},\n      escalation: '${escapeDartString(entry.escalation)}',\n      tags: ${dartList(entry.tags)},\n      aliases: ${dartList(entry.aliases)},\n      source: '${escapeDartString(entry.source)}',\n      sourceUrl: '${escapeDartString(entry.sourceUrl)}',\n      priority: ${entry.priority},\n      locale: '${entry.locale}',\n      severity: '${entry.severity}',\n    )`).join(',\n');

const dartSource = `// Auto-generated by scripts/build_offline_knowledge.mjs\nimport '../models/knowledge_models.dart';\n\nfinal List<KnowledgeEntry> generatedKnowledgeEntries = <KnowledgeEntry>[\n${dartEntries}\n];\n`;
await mkdir(path.dirname(dartOutput), { recursive: true });
await writeFile(dartOutput, dartSource);

console.log(`Downloaded ${downloadedSources.length} sources and generated ${dedupedEntries.length} knowledge entries.`);
