#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any

import generate_app_store_localizations as appstore

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = ROOT / ".artifacts/fastlane-deliver"
SOURCE_SCREENSHOTS = ROOT / ".artifacts/app-store-localization-package/screenshots"
FASTLANE_SCREENSHOT_SIZE = (1284, 2778)
METADATA_FIELDS = {
    "appName": "name.txt",
    "subtitle": "subtitle.txt",
    "promotionalText": "promotional_text.txt",
    "description": "description.txt",
    "keywords": "keywords.txt",
    "releaseNotes": "release_notes.txt",
    "supportUrl": "support_url.txt",
    "marketingUrl": "marketing_url.txt",
    "privacyPolicyUrl": "privacy_url.txt",
}


def records_for_version(version: str) -> list[dict[str, Any]]:
    appstore.APP_STORE_VERSION = version
    return [appstore.normalized_record(record) for record in appstore.LOCALE_DATA]


def clean_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def write_metadata(records: list[dict[str, Any]], output: Path) -> None:
    metadata_root = output / "metadata"
    clean_dir(metadata_root)
    for record in records:
        locale_dir = metadata_root / record["appleLocale"]
        locale_dir.mkdir(parents=True, exist_ok=True)
        for json_field, filename in METADATA_FIELDS.items():
            value = str(record[json_field]).strip()
            (locale_dir / filename).write_text(value + "\n", encoding="utf-8")


def write_fastlane_screenshot(source: Path, target: Path) -> None:
    try:
        from PIL import Image
    except Exception as exc:  # pragma: no cover
        raise RuntimeError("Pillow is required to export fastlane screenshots.") from exc

    with Image.open(source) as image:
        if image.size == FASTLANE_SCREENSHOT_SIZE:
            shutil.copy2(source, target)
            return
        image = image.convert("RGB").resize(FASTLANE_SCREENSHOT_SIZE, Image.Resampling.BILINEAR)
        image.save(target, format="PNG", compress_level=1)


def copy_screenshots(records: list[dict[str, Any]], output: Path, source_root: Path) -> None:
    screenshots_root = output / "screenshots"
    clean_dir(screenshots_root)
    missing: list[str] = []
    for record in records:
        locale = record["appleLocale"]
        source_dir = source_root / locale / "iphone-6.3"
        target_dir = screenshots_root / locale
        target_dir.mkdir(parents=True, exist_ok=True)
        for filename in record["screenshotFiles"]:
            source = source_dir / filename
            if not source.exists():
                missing.append(str(source.relative_to(ROOT)))
                continue
            write_fastlane_screenshot(source, target_dir / filename)
    if missing:
        joined = "\n".join(f"- {item}" for item in missing)
        raise FileNotFoundError(f"Missing screenshot files:\n{joined}\nRun npm run appstore:screenshots first.")


def write_manifest(records: list[dict[str, Any]], output: Path, version: str) -> None:
    manifest = {
        "version": version,
        "appIdentifier": "com.beacon.sos",
        "appleAppId": "6772494235",
        "teamId": "CX8YS634JU",
        "metadataPath": str((output / "metadata").relative_to(ROOT)),
        "screenshotsPath": str((output / "screenshots").relative_to(ROOT)),
        "screenshotSize": f"{FASTLANE_SCREENSHOT_SIZE[0]}x{FASTLANE_SCREENSHOT_SIZE[1]}",
        "locales": [record["appleLocale"] for record in records],
        "screenshotCount": len(records) * len(appstore.SCREENSHOT_STATES),
    }
    (output / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Export Beacon App Store metadata/screenshots to fastlane deliver structure.")
    parser.add_argument("--version", default=appstore.DEFAULT_APP_STORE_VERSION, help="App Store version string for localized release notes.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Output directory for fastlane deliver package.")
    parser.add_argument("--screenshots", default=str(SOURCE_SCREENSHOTS), help="Source screenshot root generated by scripts/generate_app_store_localizations.py.")
    args = parser.parse_args()

    output = Path(args.output).expanduser().resolve()
    source_root = Path(args.screenshots).expanduser().resolve()
    output.mkdir(parents=True, exist_ok=True)
    records = records_for_version(args.version)
    write_metadata(records, output)
    copy_screenshots(records, output, source_root)
    write_manifest(records, output, args.version)
    print(f"fastlane metadata: {output / 'metadata'}")
    print(f"fastlane screenshots: {output / 'screenshots'}")
    print(f"locales: {len(records)}")
    print(f"screenshots: {len(records) * len(appstore.SCREENSHOT_STATES)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
